"""Multi-agent trading pipeline runtime package.

The fund-level engine is exposed as :mod:`fund_engine`. The legacy :mod:`mas07`
module remains as the implementation/compatibility path used by the existing
notebooks. The notebooks in ``notebooks_v2/`` are generated by inlining these
modules' source (see ``notebooks_v2/_nbinline.py``) and import nothing at
runtime; this package is the importable, single-source-of-truth copy.
"""
from .mas07 import *  # noqa: F401,F403  (engine API: bracket_run, sharpe, OOS_START, ...)
from . import agent_eval, coordinators, crossasset_agent, fund_engine, mas07, rule_agents  # noqa: F401

__all__ = ["fund_engine", "mas07", "rule_agents", "crossasset_agent", "agent_eval", "coordinators"]
